---
# markdownlint-cli2 configuration
config:
  # Line length rule
  MD013:
    line_length: 120
    tables: false
    code_blocks: false

  # Allow inline HTML
  MD033: false

  # Allow duplicate headings in different files
  MD024:
    siblings_only: true

  # Allow first line not to be H1
  MD041: false

# Include patterns
globs:
  - "**/*.md"
  - "**/*.markdown"

# Exclude patterns
ignores:
  - "node_modules/**"
  - ".git/**"
  - "**/.git/**"
