---
# Backend Abstraction Layer: Check for existing credentials
# =========================================================
# Uses pluggable secret backend (1password, infisical, ansible_vault)
# to check if API keys already exist before creating new ones.
#
# WARNING: POTENTIAL SILENT FAILURE SCENARIO
# On FRESH Komodo deployments with STALE credentials in the secret backend,
# this check will skip API key creation, causing failures in subsequent playbooks.
#
# SOLUTION: Use komodo_auth_force_recreate=true to force regeneration
#   ansible-playbook playbooks/03_komodo_auth.yml -e komodo_auth_force_recreate=true

- name: "Check if API keys already exist in {{ komodo_auth_secret_backend }}"
  ansible.builtin.include_tasks: "backends/{{ komodo_auth_secret_backend }}.yml"
  vars:
    operation: "check"

- name: Show API key recreation notice when forcing recreation
  ansible.builtin.debug:
    msg:
      - "🔄 Force recreation enabled - will recreate API keys"
      - "   Backend: {{ komodo_auth_secret_backend }}"
      - "⚠️  This will overwrite existing API keys!"
  when:
    - komodo_auth_existing_api_key.stdout != ""
    - komodo_auth_force_recreate | default(false) | bool

- name: Skip authentication setup if API keys already exist (unless force recreate)
  ansible.builtin.meta: end_play
  when:
    - komodo_auth_existing_api_key.stdout != ""
    - not (komodo_auth_force_recreate | default(false) | bool)

- name: Wait for Komodo Core to be ready
  ansible.builtin.uri:
    url: "{{ komodo_auth_base_url }}"
    method: GET
    status_code: 200
  retries: 10
  delay: 5

- name: Test if admin user already exists
  ansible.builtin.uri:
    url: "{{ komodo_auth_base_url }}/auth"
    method: POST
    headers:
      Content-Type: "application/json"
    body_format: json
    body:
      type: "LoginLocalUser"
      params:
        username: "{{ komodo_auth_admin_username }}"
        password: "{{ komodo_auth_admin_password }}"
    status_code: [200, 500] # 200 = success, 500 = user doesn't exist
  register: komodo_auth_login_test
  failed_when: false
  no_log: true

- name: Handle fresh deployment if admin user doesn't exist
  ansible.builtin.include_tasks: create_admin_user.yml
  when:
    - komodo_auth_login_test is defined
    - komodo_auth_login_test.status is defined
    - komodo_auth_login_test.status != 200

- name: Login as admin user
  ansible.builtin.uri:
    url: "{{ komodo_auth_base_url }}/auth"
    method: POST
    headers:
      Content-Type: "application/json"
    body_format: json
    body:
      type: "LoginLocalUser"
      params:
        username: "{{ komodo_auth_admin_username }}"
        password: "{{ komodo_auth_admin_password }}"
    status_code: 200
  register: komodo_auth_login_response
  no_log: true

- name: Extract JWT token
  ansible.builtin.set_fact:
    komodo_auth_jwt_token: "{{ komodo_auth_login_response.json.jwt }}"
  no_log: true

- name: Create or find service user
  ansible.builtin.include_tasks: manage_service_user.yml

- name: Create API key for service user
  ansible.builtin.include_tasks: create_api_key.yml

- name: "Store API credentials in {{ komodo_auth_secret_backend }}"
  ansible.builtin.include_tasks: "backends/{{ komodo_auth_secret_backend }}.yml"
  vars:
    operation: "store"
