---
galaxy_info:
  author: basher83
  description: Ansible role for managing Komodo
  company:
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - all
  galaxy_tags:
    - komodo
    - management
    - infrastructure
dependencies: []
