---
# Ansible requirements for Homelab Komodo infrastructure
# Install with: ansible-galaxy install -r requirements.yml

# External roles for infrastructure management
roles:
  # Docker installation and management
  - name: geerlingguy.docker
    version: "7.6.0"

  # Komodo periphery deployment with systemd
  - name: bpbradley.komodo

# Required collections
collections:
  # Docker management modules
  - name: community.docker
    version: ">=3.4.0"

  # General utilities including 1Password lookups
  - name: community.general
    version: ">=8.0.0"

  # Infisical secrets management
  # Requires Python package 'infisicalsdk' on the controller/Execution Environment
  - name: infisical.vault
    version: ">=1.1.3"

  # Additional useful collections
  - name: ansible.posix
    version: ">=1.5.0"

  - name: ansible.utils
    version: ">=2.10.0"