#!/usr/bin/env bash
#MISE description="Install project dependencies"
#MISE depends=["pip:install", "ansible:install"]

if [ ! -f .vscode/settings.json ]
then
    echo "No .vscode/settings.json found, copying from mise template."
    mkdir -p .vscode
    cp mise-tasks/templates/settings.json .vscode/settings.json
fi